### ISSUE TITLE
Cannot include another grammar's pattern in an includeOnlyRule

### ISSUE THREAD

**Issue by matter123** [microsoft/vscode-textmate#105]
Reference repository: https://github.com/matter123/vscode-textmate-include-nested

If a pattern in the grammars repository includes a pattern from another grammar, and a pattern includes that pattern, the other grammar's pattern is not applied.

In the reference repository, `grammarA` has the pattern `#test2` that matches `some test pattern`. `grammarB` has the pattern `#test2` that includes `source.test#test2` (grammarA's pattern). When `grammarB` includes `#test2` (from `#test`), the grammar does not match `some_test_pattern`.

**Comment by alexandrudima** [comment]
I think the problem lies in the way `grammarB` includes the rule from `grammarA`.

Specifically, `vscode-textmate` expects a `patterns` property in order to include something:
`grammarB.tmLanguage.json`:
![image](https://user-images.githubusercontent.com/5047891/63117422-0f0fae00-bf9c-11e9-9256-db18b74abf2c.png)

**Comment by matter123** [comment]
Textmate sets the scope of `some test pattern` when grammarB includes `source.test#test2` directly.

<img width="486" alt="Screen Shot 2019-08-15 at 12 05 31" src="https://user-images.githubusercontent.com/714007/63119611-6dfe0480-bf55-11e9-879a-46e07f00ddca.png">

GrammarB:
```plist
{	patterns = (
		{	include = '#test'; },
		{	include = '#embedded'; },
	);
	repository = {
		test = {
			begin = 'testStart';
			end = 'testEnd';
			patterns = ( { include = '#test2'; } );
		};
		'test2' = { include = 'source.test#test2'; };
	};
}
```
