### ISSUE TITLE
Problem with natural numbers

### ISSUE THREAD

**Issue by BenFradet** [microsoft/vscode-textmate#112]
I'm at a bit of a loss as to why this is happening so I thought I'd ask here. Following is a small reproduction of what I'm trying to achieve.

I have the following grammar:

```json
{
  "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
  "name": "Unison",
  "patterns": [{
    "match": "([^\\+\\-\\w\\d]|^)(\\d+)",
    "captures": {
      "2": {
        "name": "constant.numeric.integer.unsigned.unison"
      }
    }
  },{
    "match": "([^\\w\\d]|^)([+-]\\d+)",
    "captures": {
      "2": {
        "name": "constant.numeric.integer.signed.unison"
      }
    }
  }],
  "scopeName": "source.u"
}
```

if I build a `Grammar` from this json and try to tokenize `+42`, I get as `tokens`

```js
[ { startIndex: 0,
    endIndex: 3,
    scopes: [ 'source.u', 'constant.numeric.integer.signed.unison' ] } ]
```

which is expected.

However when I tokenize `42`, I get:

```js
[ { startIndex: 0, endIndex: 3, scopes: [ 'source.u' ] } ]
```

without the unsigned scope.

**Comment by msftrncs** [comment]
Its because your first part of the rule says that you cannot match a digit, and the 4 is a digit.  I bet ` 42` '(space)42' works.

I think you meant the first part to be a look behind.   I recommend staying away from look behinds.   Always try matching going forward, as looking behind can set you up for things that are not the way they seem.   For instance, looking behind for a quote, was the quote escaped?  You'd have to look behind further, but wait, was the escape escaped?   When you first start out writing a grammar you will want to use look behinds because you haven't handled much yet, but you should try to refrain from that, save the failures as TODO items .   Once everything is scoped, theres almost no reason to look behind.

**Comment by msftrncs** [comment]
For instance, just use `\b` in both rules before the numeric match.

`"match": "\\b(\\d+)"`, and `"match": "\\b([+-]\\d+)"`,

**Comment by BenFradet** [comment]
Thanks, I'm trying:

```json
{
  "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
  "name": "Unison",
  "patterns": [{
    "match": "\\b(\\d+)",
    "captures": {
      "1": {
        "name": "constant.numeric.integer.unsigned.unison"
      }
    }
  },{
    "match": "\\b([+-]\\d+)",
    "captures": {
      "1": {
        "name": "constant.numeric.integer.signed.unison"
      }
    }
  }],
  "scopeName": "source.u"
}
```

However I get the following for `+42`:

```js
[ { startIndex: 0, endIndex: 1, scopes: [ 'source.u' ] },
  { startIndex: 1,
    endIndex: 3,
    scopes: [ 'source.u', 'constant.numeric.integer.unsigned.unison' ] } ]
```

**Comment by BenFradet** [comment]
The original example actually works as expected, I was reusing the registry with the whole grammar, that's why I got false positives.

The look behind must indeed conflict with another part of the grammar, thanks a lot for your help.

**Comment by msftrncs** [comment]
You're welcome, sorry for my error,  (\b) doesn't match at the beginning of a line.  😞 it would have really needed `(?:\\b|^)`.

**Comment by msftrncs** [comment]
For clarification, I am still not quite right.   `\b` always gives me trouble.  `\b` works like a look behind (hence it should be refrained from being used) as `(?<=\w)(?=\W)|(?<=\W)(?=\w)`.  So, '(space)+' doesn't count as a \b between the space and the '+', so it fails.   It would instead require:

`"match": "\\b(\\d+)"`, and `"match": "(?<=\W|^)([+-]\\d+)"`,

This just demonstrates why look behinds should be avoided.   Instead, all text should be matched by rules looking in the forward direction only.  Only use look-behinds when you know exactly what could have been matched previously.
