### ISSUE TITLE
Parsing a code snippet

### ISSUE THREAD

**Issue by janko** [microsoft/vscode-textmate#116]
I'm trying to use this library in order to tokenize code snippets in a markdown file (and later syntax highlight them using CSS). However, I'm not able to figure out how to use this library to tokenize a multiline string of code using a selected language.

**Comment by jeff-hykin** [comment]
Here's an example for a python snippet. This isn't exact code, I didn't test it, but it should give you an idea of how to use the library.

If you're not sure where to get a textmate grammar, here's an example of a python textmate grammar. https://github.com/MagicStack/MagicPython/blob/master/grammars/MagicPython.tmLanguage


```javascript
const fs = require('fs')
const vsctm = require('vscode-textmate')

// one helper function
const pathToATextmateGrammarForPython = "./PATH_TO_PYTHON_GRAMMAR"
async function getPythonTokens(yourString) {
    const openFileAsAPromise = new Promise((resolve, reject) => fs.readFile(pathToATextmateGrammarForPython, (e,d)=>e?reject(e):resolve(vsctm.parseRawGrammar(d.toString()))))
    const aGrammarThatExplainsHowToParsePython = new vsctm.Registry({loadGrammar:()=>openFileAsAPromise })
    return new Promise((resolve, reject) => {
        let allTokens = []
        aGrammarThatExplainsHowToParsePython.loadGrammar().then(grammar => {
            let ruleStack = vsctm.INITIAL
            for (let line in yourString.split('\n')) {
                const lineTokens = grammar.tokenizeLine(line, ruleStack)
                ruleStack = lineTokens.ruleStack
                allTokens = allTokens.concat(lineTokens)
            }
            resolve(allTokens)
        }).catch(e=>reject(e))
    })
}

// actually the part you want (multiline string of code)
getPythonTokens(`
def a_python_function():
    print('this is python code')
`)

```

The value returned by `await getPythonTokens()` will be a list of tokens, each token will contain  TM scopes. For example the `a_python_function` should have the scope "entity.name.function.python". You can use these scopes to set CSS classes

**Comment by janko** [comment]
Thanks for the reply.

The library I'm trying to integrate tokenization with doesn't support promises, but I've found [atom/highlights](https://github.com/atom/highlights), which uses the [atom/first-mate](https://github.com/atom/first-mate), which supports synchronous loading of grammars. This library perfectly suits my needs.
