### ISSUE TITLE
Does this library support C/C++ Label?

### ISSUE THREAD

**Issue by MxDany** [microsoft/vscode-textmate#120]
Does this library support C/C++ Label, just like this
![image](https://user-images.githubusercontent.com/20413031/69954292-e7862680-1535-11ea-84ae-107708829e9b.png)

**Comment by msftrncs** [comment]
@MxDany, no, this repository / library supports the TextMate file that does what you see.  But it is up to the TextMate grammar file to specifically support a construct such as a C/C++ label.

VSCODE-TEXTMATE is just an engine to process source files according to a TextMate grammar.

A TextMate grammar describes languages such as C/C++, allowing a theme to be applied.

VSCODE-TEXTMATE is also an engine to apply a theme to the results of a source file after it has been processed according to the TextMate grammar.

**Comment by MxDany** [comment]
> @MxDany, no, this repository / library supports the TextMate file that does what you see. But it is up to the TextMate grammar file to specifically support a construct such as a C/C++ label.
> 
> VSCODE-TEXTMATE is just an engine to process source files according to a TextMate grammar.
> 
> A TextMate grammar describes languages such as C/C++, allowing a theme to be applied.
> 
> VSCODE-TEXTMATE is also an engine to apply a theme to the results of a source file after it has been processed according to the TextMate grammar.

Sorry, i didn't fully understand, does this repository construct C/C++ Label? cause i didn't see the specific implementation of C/C++ Label. or can you tell me which 'scope' i can use to identify C/C++ Label, so i can highlight the C/C++ Label. such as, i can use "entity.name.function.preprocessor" to identify C/C++ preprocessor.

**Comment by msftrncs** [comment]
To help clarify, this repository is a library that utilizes files, such as the ones contained at https://github.com/jeff-hykin/cpp-textmate-grammar/tree/master/syntaxes, to process a source code file in to tokens and scopes, and then apply theme to allow an editor to color the source code.

This repository/library does not directly support any specific language.   Other repositories provide `grammar` files, that handle the various languages, and such, there can be many different implementations of `grammar` for any given language, and such, the final token/scope/theme output from this repository can vary wildly.

A quick check, the C/C++ repository above does support C/C++ labels, but you might find that the common theme's do not, as labels are both infrequently used or infrequently themed.  I had to add support for them in my own personal theme.
