### ISSUE TITLE
microbug / edge case in \A / \G replacement code

### ISSUE THREAD

**Issue by asottile** [microsoft/vscode-textmate#126]
I'm implementing a similar highlighter for a [terminal text editor](https://github.com/asottile/babi) and have been using this as a great resource / reference implementation

I've ~essentially implemented this routine bug-for-bug in my implementation: https://github.com/microsoft/vscode-textmate/blob/8961b1554acbb649bdce0d236ab0fd78180447af/src/rule.ts#L192-L240

one thing that was pointed out by my twitch chat yesterday that this routine can mangle some "valid" (but weird) regexes if `\A` / `\G` appears inside a character class

consider the following:

```pycon
>>> import onigurumacffi
>>> reg = onigurumacffi.compile(r'[\ABC]+')
>>> reg.match('ABC\\')
<onigurumacffi._Match span=(0, 3) match='ABC'>
```

(the backslash here is apparently ignored by the engine 🤷‍♂)

the routine above mangles this regex to `[\\ufffBC]+` which doesn't match:

```pycon
>>> from babi.reg import make_reg
>>> reg = make_reg(r'[\ABC]+')
>>> reg.match('ABC\\', pos=0, first_line=True, boundary=False)
<onigurumacffi._Match span=(0, 3) match='ABC'>
>>> reg.match('ABC\\', pos=0, first_line=False, boundary=False)
>>> 
```

just an interesting tidbit -- I don't know of any grammars this affects in the wild and seems exceedingly rare that this is an actual problem but figured I'd point it out anyway -- thanks for the easy interface, it definitely made [testing grammars much easier](https://github.com/asottile/textmate-highlight/blob/master/vsc_test/vsc.js)

___

an aside (that I can't confirm since I didn't do it myself) -- it seems that textmate doesn't do any special handling for \A (and maybe not even \G, I didn't look too hard) so I'm wondering where that came from?  (someone in my chat was testing out some grammars against textmate to validate some of these assumptions and was getting different results from the vscode textmate parser -- I can try and get more concrete information if interested, though I suspect this is already known)

**Comment by asottile** [comment]
also a micro optimization in this routine can be made by using `.index(...)` / `substring` to search ahead for the next `\` instead of going character-by-character -- not sure how important the performance is for vs code but it made a significant difference in my python implementation (here's [the python code I have for that](https://github.com/asottile/textmate-highlight/blob/3924a0397924def3f9a54ecc431689fbd9b2cb93/highlight_demo/reg.py#L23-L30))

**Comment by asottile** [comment]
by the way, it looks like `oniguruma` will have runtime flags for disabling these anchors in the next version: https://github.com/kkos/oniguruma/issues/198

**Comment by alexdima** [comment]
Adopted via https://github.com/microsoft/vscode-textmate/commit/1aec0873bce7b00dd899c127a43ef6e27ef4e72f
