### ISSUE TITLE
Raku syntax highlighting of in-line comments and comma-separated arrays

### ISSUE THREAD

**Issue by Sleepful** [microsoft/vscode-textmate#129]
After the `#` symbol, everything is colored as a comment, even though the comment should end at the last `)` parenthesis and the `'t';` are not part of the comment.

```raku
my $bool = so #`(forces bool, or ?$variable) 't';
```

The following is another issue I saw where only the first element of the array is colored as a string, the rest are not colored

```raku
my @arraySigil = 'a','b','c';
```

**Comment by alexdima** [comment]
@Sleepful Please report this against the TM grammar project, `vscode-textmate` is the interpreter for all the grammars, it does not maintain a specific TM grammar.
