### ISSUE TITLE
Trouble correctly parsing C++: single token containing two identifiers with space in between

### ISSUE THREAD

**Issue by kshetline** [microsoft/vscode-textmate#130]
I'm somehow getting a token that really should be two tokens, a type declaration and a variable, reported as a single token, including the space between those two things.

It's in this bit of C++ code:
```c++
Napi::Value addSensorDataListener(const Napi::CallbackInfo &info) {
  Napi::Env env = info.Env();

  if (info.Length() < 2) {
    Napi::TypeError::New(env, "2-3 arguments should be provided").ThrowAsJavaScriptException();
    return env.Undefined();
  }
  ...
```
In the second line above, I'm getting "`Env env`" in a single token. The scope for the token is `source.cpp.embedded.macro`, which I think is the surrounding scope in which this broken token is embedded.

The full original file is here:https://github.com/kshetline/rpi-acu-rite-temperature/blob/master/ar-signal-monitor-node.cpp

What's odd is that syntax coloring is rendering the uppercase `Env` part in one color, and the lowercase `env` part in another, so at some level VSCode must be parsing this C++ code better than the results I'm getting back from TextMate. The grammar I'm using is the one included with VSCode 1.44.2 on MacOS.

**Comment by jeff-hykin** [comment]
Hey @kshetline, try filling out the issue template on [https://github.com/jeff-hykin/cpp-textmate-grammar](https://github.com/jeff-hykin/cpp-textmate-grammar)  (the upstream source for VS Code C++ textmate). It could be an issue with the C++ extension, but if not then https://github.com/jeff-hykin/cpp-textmate-grammar will be the place for the bug.

**Comment by kshetline** [comment]
Interesting. I see what you show above for a split second, with `Env env` in white, with no differentiation, but then it updates to this, where `Env` and `env` are colored differently:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/24473229/80821891-9becad00-8ba7-11ea-8163-4a83da9a7ec3.png">

This appears to be the work of the C/C++ IntelliSense extension, because if I disable that, my syntax coloring remains the same as your screenshot.

Does the fact that IntelliSense makes a difference here offer you any clues as to where I should focus on finding this problem?

**Comment by alexdima** [comment]
This is very likely the semantic highlighting that comes on top of TM coloring. Please open an issue directly against the C++ extension at https://github.com/Microsoft/vscode-cpptools/issues
