### ISSUE TITLE
Expose `SyncRegistry#getDefaults` on `Registry`.

### ISSUE THREAD

**Issue by DylanPiercey** [microsoft/vscode-textmate#133]
Currently `getColorMap` is exposed from the sync registry, however, the defaults styles discovered when parsing the are only accessible currently via the private api:

```js
registry._syncRegistry.getDefaults() // Returns ThemeTrieElementRule
```

I propose that `getDefaults` is exposed from `Registry` as well.
This would be a one-liner change that I am happy to make a PR for.

**Comment by alexdima** [comment]
The `ThemeTrieElementRule` is not part of the API and IMHO is an implementation detail of theming. What would you really want from this new API?

**Comment by DylanPiercey** [comment]
I think the main thing I was looking for really was `registry.getColorMap();`. Technically there can be other defaults in the theme (eg selection color & line highlight color) that there doesn't appear to be a good way to access.

For the most part though `foreground` and `background` are enough. I'll close this issue.
