### ISSUE TITLE
`SyncRegistry#getDefaults` missing some theme meta data.

### ISSUE THREAD

**Issue by DylanPiercey** [microsoft/vscode-textmate#134]
According to the [`textmate theme docs`](https://macromates.com/manual/en/themes) a textmate theme rule contains the following properties: `background, foreground, caret, selection, invisibles, line highlight color`. Ideally these would also be discovered and added to the result of `SyncRegistry#getDefaults()`.

My personal use case is to use this module to inject a `tmTheme` in monaco. Right now I can configure the monaco theme's default `editor.foreground` and `editor.background`, however these other properties I am not able to see without analyzing the `tmTheme` myself.

**Comment by alexdima** [comment]
The scope of `vscode-textmate` is limited to tokenization. Thus, it does not read or do anything with `caret`, `selection`, `invisibles`, `line highlight color`, since those are colors useful for an editor, not for a tokenizer.
