### ISSUE TITLE
Default fg/bg should be reversed for dark theme

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-textmate#138]
https://github.com/microsoft/vscode-textmate/blob/2fe5a125bb79e1acd85a449f2636d3afce0de8bc/src/theme.ts#L183-L184

When parsing a theme, the parser should detect whether the theme is a light one. If so, foreground should be light and background should be dark.

Related: https://github.com/shikijs/shiki/issues/45

**Comment by alexdima** [comment]
I don't quite agree.

IMHO a theme must have an entry without a scope in order to define the defaults.

I don't think there should be any magic auto-detectiong for light / dark themes based on other colors defined in the theme for other scopes.

**Comment by octref** [comment]
@alexdima OK, I can take that position. Would love you to chime in here though https://github.com/microsoft/vscode/pull/105418
