### ISSUE TITLE
TextMate scope for Java keyword "super" is missing

### ISSUE THREAD

**Issue by OzelotVanilla** [microsoft/vscode-textmate#144]
The keyword "this" has special textmate scopes like the picture below.

<a href="https://user-images.githubusercontent.com/59910575/105008390-25b11300-5a74-11eb-96d6-92e54ddfa9e5.png"><img src="https://user-images.githubusercontent.com/59910575/105008390-25b11300-5a74-11eb-96d6-92e54ddfa9e5.png" width=400px></a>

However, the keyword "super" not has one.

<a href="https://user-images.githubusercontent.com/59910575/105008710-8b9d9a80-5a74-11eb-9417-5bd3cc59d3ea.png"><img src="https://user-images.githubusercontent.com/59910575/105008710-8b9d9a80-5a74-11eb-9417-5bd3cc59d3ea.png" width=400px></a>

I am first time to ask question, and I do not know whether I have found the right place to ask it. If there is anything wrong in my writing or asking, please feel free to tell me, thank you!

**Comment by msftrncs** [comment]
The keyword is scoped, it is scoped `keyword.language.java`.  If you feel it must be more specifically scoped, the issue is in the [Language-Java](https://github.com/atom/language-java) repository.
