### ISSUE TITLE
C++ and clangd: syntax highlighting is broken when present "[[" inside disabled by #if / #endif code

### ISSUE THREAD

**Issue by timofeev-n** [microsoft/vscode-textmate#156]
Just redirecting issue from [clangd's bug tracker](https://github.com/clangd/clangd/issues/882):

**The syntax hightlights is broken when '[[' appears inside disabled by #if / #endif code**

```
#include "pch.h"

class MyClass {
public:
  MyClass(const char* name): m_name(name)
  {}
#if ENGINE_OS_MACOS  // ENGINE_OS_MACOS is undefined, so code below does not affects on compilation and must behave like comment
	[[AppDelegate GetInstance] setActiveInBackground : true];
#endif
   // FROM HERE SYNTAX HIGHLIGHING IS BROKEN
  const std::string  m_name;
};

int main() {
  MyClass instance("Sample");
  return 0;
}
```

The same behaviour will be if writing just:
```c++
#if 0
	[[
#endif // all code below will not be highlighted properly
```
--------------
Below [comment](https://github.com/clangd/clangd/issues/882#issuecomment-931925028) why this issues should be addressed to vscode team:

> I tried this, and what I'm seeing is that clangd's semantic highlighting remains correct after the disabled section, but the lexical highlighting (textmate tokens) are broken.
> 
> The lexical highlighting is handled on the client side ==> this is a vscode issue, not a clangd issue.

**Comment by HighCommander4** [comment]
I believe this issue pertains to the [better-cpp-syntax](https://github.com/jeff-hykin/better-cpp-syntax) repository rather than this one, and I filed it as https://github.com/jeff-hykin/better-cpp-syntax/issues/569.

I think this issue can be closed.

**Comment by timofeev-n** [comment]
Ok, thank you again. I will check it immediately.
