### ISSUE TITLE
Support for `FontStyle.Strikethrough` (tracking issue)

### ISSUE THREAD

**Issue by SNDST00M** [microsoft/vscode-textmate#158]
> Just a note for anyone looking into this: for text grammars, it seems that adding an extra font-style will not play nicely with the current binary format we use for tokens

> Such a change needs to begin in the project vscode-textmate. The bit encoding format for tokens is defined in that project at:

https://github.com/microsoft/vscode-textmate/blob/a53ae3c12bef5499a7dc548b3058ee64bfcbd222/src/main.ts#L201-L233

> Adding the strikethrough font style would require four bits instead of three

> Once that project has a new token bit encoding format, it needs to be published with a new major version (since this is a breaking change) and then adopted in VS Code.

> Also, the enums are powers of 2 because they represent bits, so `FontStyle.Strikethrough` would be 8. But for it to be 8, then all the other information bits need to be shifted by 1.

**Comment by alexdima** [comment]
To make room for it, I think `StandardTokenType` could be shrinked to only 2 bits (it has only 4 possible values: Other, Comment, String, RegEx and they don't need to be masks).

**Comment by SNDST00M** [comment]
Awesome! Normally I would start work on this immediately but I have to port my Textmate LSP to the browser and its a rather involved task because of the moving parts. I could get to this in the New Year? 🤔

**Comment by SNDST00M** [comment]
Draft PR at #159
