### ISSUE TITLE
Support ELECTRON_RUN_AS_NODE

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-textmate#16]
Our next update of Electron will remove the deprecated ATOM_SHELL_INTERNAL_RUN_AS_NODE. To support both old and new world, I suggest to set both flags wherever you set ATOM_SHELL_INTERNAL_RUN_AS_NODE currently.

**Comment by alexandrudima** [comment]
@bpasero What Electron version will deprecate this?

**Comment by bpasero** [comment]
@alexandrudima anything > 1.0. (we are still on 0.37.x)

**Comment by alexandrudima** [comment]
I removed the script that was using `ATOM_SHELL_INTERNAL_RUN_AS_NODE`
