### ISSUE TITLE
0-infinite quantifier inside look behind capture group causes tremendous performance loss

### ISSUE THREAD

**Issue by RedCMD** [microsoft/vscode-textmate#166]
Creating a syntax highlighter with the following code and running it on a single line file filled with thousands of the letter `c` will cause tremendous lag
![image](https://user-images.githubusercontent.com/33529441/148741438-16ba238c-fb79-4c1f-a454-7618164b5fe2.png)
```json
{
	"name": "Lag Syntax",
	"scopeName": "source.redcmd.syntax.lag",
	"patterns": [
		{
			"match": "(?<=ab*)c",
			"name": "strong keyword.control"
		}
	]
}
```
Replacing the `*` with a `+` or changing the regex to `(?<=ab+|a)c` will remove all lag and allow my machine to easily interpret a million character single line file
But then a file filled with `bc` will lag instead

I cant seem to figure out how the engine matches lookbehinds
does it start with the `c` first then try to match the lookbehind afterwards?
or does it try to match the lookbehind first, then the `c`?

using `{0,10000}` instead of `*` reduces lag massively
which seems to suggest that the engine is trying to match `b` an infinite amount (or an internal limit) of times before giving up
but for some reason it only does so when its allowed to match 0 times??
maybe its an underflow error?

But then using the regex `(?<=a(b+)?)c` also causes an enormous amount of lag
which I don't get
unless.. `(b+)?` gets optmized to `b*`

or maybe cause the engine backtracks in the wrong direction and ends up endlessly rechecking `b`?                
  

    
  
Noticed single line files were only getting partially highlighted
![image](https://user-images.githubusercontent.com/33529441/148746246-b75913ec-ffac-470e-bfba-8dfee4b67873.png)
Dug around and found out it was caused by this regex:
![image](https://user-images.githubusercontent.com/33529441/148745623-56f18986-6eb7-4f95-80f0-913839045649.png)
`(?<={\\d*)\\\\{2}` is the part that was going over board on every single `\\`

**Comment by jeff-hykin** [comment]
This might be causing some of the serious performance issues in the C++ syntax as well. 

Part of our preprocessing steps in the C++ grammar optimize (b+)? to become b* so that's probably not doing us any favors

**Comment by RedCMD** [comment]
I just looked through all `c`, `cpp`, `cpp.embed` and `cuda-cpp` grammar files and did _not_ see this specfic issue once.

**Comment by jeff-hykin** [comment]
Oh, well thanks for saving me the trouble @RedCMD. I suppose it's just regular catastrophic backtracking then for C++

**Comment by RedCMD** [comment]
@jeff-hykin
This may be causing a lot of the C++ performance issues
I notice many `"#inline_comment"` includes under captures
https://github.com/microsoft/vscode-textmate/issues/167

**Comment by alexdima** [comment]
Thank you for reaching out! I think the regex `(?<=ab*)c` might be running into catastrophic backtracking. Unfortunately, I don't know enough about the inner workings of a regex engine to help deeper than that. We are using [`oniguruma`](https://github.com/kkos/oniguruma) as the underlying regular expression engine. The author of `oniguruma` has been incredibly helpful and responsive in the past.

@kkos do you think there are optimization opportunities in oniguruma around such regular expressions?
