### ISSUE TITLE
Jade colorizing broken after fix for 2.1.1

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-textmate#18]
The change for 2.1.1 broke the syntax highlighting tests at unexpected places:

Before:
https://github.com/Microsoft/vscode/blob/master/extensions/jade/test/colorize-fixtures/test.jade
![image](https://cloud.githubusercontent.com/assets/6461412/17748172/6a7f1524-64b8-11e6-9b14-4ee4f5ddb591.png)

After
![image](https://cloud.githubusercontent.com/assets/6461412/17748182/7ab7fde8-64b8-11e6-93aa-117289fc05aa.png)

See lines 14 and 27.

**Comment by aeschli** [comment]
Note that I updated the vscode syntax colorizing tests to the new colorizing outputs of 2.1.1, as to keep our tests green.

**Comment by alexandrudima** [comment]
@aeschli Sorry for breaking the tests, `tests\run-integration.bat` does not execute the tokenization tests on Windows

**Comment by alexandrudima** [comment]
After investigation, I have found the following:

* From http://jade-lang.com/reference/code/
![image](https://cloud.githubusercontent.com/assets/5047891/17771501/95d70f3e-6543-11e6-96e3-1162c972520d.png)

The grammar contains a rule for unbuffered code: https://github.com/Microsoft/vscode/blob/7744fff09466a74c42b3ee9e84275e5b75165d1e/extensions/jade/syntaxes/Jade.json#L282

But note how this rule is not matched unless the line starts with at least one whitespace:
```
		{
			"begin": "^\\s+",
			"comment": "All constructs that generally span a single line starting with any number of white-spaces.",
			"end": "$",
			"patterns": [
				{
					"include": "#inline_jade"
				},
				{
					"include": "#blocks_and_includes"
				},
				{
					"include": "#unbuffered_code"
				},
```

I believe the fix I did exposes this issue in the grammar.
