### ISSUE TITLE
`main.d.ts` no longer in version control

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/vscode-textmate#19]
Is there a reason the `main.d.ts` declaration file is no longer in the repo?

I see that the `release.js` creates it, but it would really help me out if you guys could go back to tracking it under version control. It may seem like an odd request, but that file is actually pretty crucial to a project I'm working on.

I'm currently working on a helper extension for the syntax grammars used by the [Ionide-FSharp](https://marketplace.visualstudio.com/items?itemName=Ionide.Ionide-fsharp) extension for vscode.

[![syntax](https://cloud.githubusercontent.com/assets/680051/17829160/b6653204-6673-11e6-81c3-5ea1a5bfc7f8.gif)](https://github.com/ionide/ionide-fsgrammar)

The idea is to have an extension that you can keep reloading quickly to test out the changes you've made to the syntax grammars. Launch the extension, it opens to an F# file with lots of tricky syntax, make a tweak, rebuild, rinse, repeat. It's pretty sweet.

But the way we build our vscode extensions is a bit different from how everyone else does.  We use the [**fable-compiler**](https://github.com/fable-compiler) to transpile F# code into js. **[ts2fable](https://www.npmjs.com/package/ts2fable)** is the tool we use to create F# interfaces that we can code against, like this one for [the vscode api](https://github.com/fable-compiler/fable-vscode/blob/master/npm/Fable.Import.VSCode.fs), by parsing typescript declaration files. That's what I need the `main.d.ts` for. `vscode-textmate` will let me add a lot more detailed feedback information about how the source code is being tokenized.

I know the `main.d.ts` is a part of the npm module that's installed, but using that particular file in the build process we need to go through for the F# to js transpilation is a bit difficult, and we don't get the same kind of control and precision about what version of the file we want to lock into the build process.  [**Paket**](https://fsprojects.github.io/Paket/index.html) is the package manager of choice for F# and one of it's great features is setting up [github dependencies](https://fsprojects.github.io/Paket/github-dependencies.html), which lets us lock a file to a particular hash for our builds. e.g.
```
github Microsoft/vscode-textmate:master release/main.d.ts (997c9419fb1cc03256d63e1042609742b30ee7e4)
```
This is the most reliable way to have reproducible builds, which I'd like to do my best to ensure for the people willing to put the time and effort into using this extension to improve our syntax grammars.

Sorry for the long winded and convoluted explanation, but the declaration file is one of the cornerstones to what I'm working on and it'd be really great if you could help me out.

BTW - getting `node-gyp` to work on my windows machine was an absolute nightmare. Once I've whittled down the steps to the precise process without all the fiddling I had to do, I'll PR it onto the readme so no one else has to go through that mess :dizzy_face:

**Comment by cloudRoutine** [comment]
thanks!

**Comment by alexandrudima** [comment]
@cloudRoutine Nice idea! :+1:
