### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by rehmsen** [microsoft/vscode-textmate#202]
It seems releases were not tagged since v7.0.1. 

@hediet suggested:
> Can you create a issue that asks for tags on releases? It would be awesome if you could come up with a PR.
> 
> This is how we do it in the monaco editor: https://github.com/microsoft/monaco-editor/blob/main/.azure-pipelines/publish-stable.yml

**Comment by rehmsen** [comment]
I am happy to contribute, but I first need to understand the current state, and I am a bit confused:
* microsoft/vscode version 1.76.0
  * depends on microsoft/vscode-textmate 9.0.0
  * uses `diffStateStackRefEq` which was introduced in 16ac8e9 from February
* microsoft/vscode-textmate 9.0.0 was bumped in 7cf5852 and
  * that looks like it was on branch "main"
  * however oddly, the parent of 7cf5852 is f7f4a9d which is from December
  * and now I found 88baacf which looks like 7cf5852 merged into main (where I thought it was from the beginning)?

Maybe I am missing something git here, but it looks like it is 88baacf which should be tagged 9.0.0, not 7cf5852.

**Comment by hediet** [comment]
I believe https://github.com/microsoft/vscode-textmate/commit/d80e58a5ad6b4cc822483e73ad273df01e8ad2b1 is 9.0.0.

**Comment by rehmsen** [comment]
d80e58a does not have the version bump in the package.json yet though: 
https://github.com/microsoft/vscode-textmate/blob/d80e58a5ad6b4cc822483e73ad273df01e8ad2b1/package.json#L3

**Comment by hediet** [comment]
Yes, this is because I created both PRs (the feature and bumping the version) at the same time, but the version bump got reviewed earlier and thus merged earlier.
