### ISSUE TITLE
Equivalent of registry.loadGrammarFromPathSync API that doesn't touch the disk

### ISSUE THREAD

**Issue by vors** [microsoft/vscode-textmate#21]
This issue is a feature request.
In our scenario (test harness), it's desirable to instantiate grammar from a text string and not a file on the disk. Could we add such API?

**Comment by alexandrudima** [comment]
PR welcome. You can add an optional `getFileContents?(filePath:string): string` to the `IGrammarLocator` and then try that first before going to `fs` and pass some object encapsulating file reading to the two methods in `grammarReader.ts`.

**Comment by alexandrudima** [comment]
This is now supported via the `loadGrammar` indirection.

**Comment by vors** [comment]
Good!
