### ISSUE TITLE
How to find all local variables?

### ISSUE THREAD

**Issue by eterlan** [microsoft/vscode-textmate#213]
Please help! I just study this whole day and cannot get the job done..
``` textmate
		{
			"include": "#local_variable"
		}
    ],
    "repository": {
		"local_variable":{
			"name": "localvariable.gdscript",
			"match": "(?<=\\tvar\\s)\\b\\w+\\b"
		},
```
https://regex101.com/r/9siVIE/1
this works, but how to use this variable to find its usages inside function?

**Comment by RedCMD** [comment]
what you're probably wanting is [semantic highlighting](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide)
textmate should only be used for basic items
as it is tokenizes everything line by line and cant jump around

**Comment by jeff-hykin** [comment]
To support what RedCMD said, finding local variables is impossible for Textmate parser to do reliably for languages like python/C++/Java/JavaScript. It's only realistic when local variables always start/end with something like `$`.

You'll need to use an LSP, or some other custom parser to get information about local variables. If you want to highlight them, there is a "decorations" API in VS Code you can use.
