### ISSUE TITLE
PHPdoc highlighting issue

### ISSUE THREAD

**Issue by eexit** [microsoft/vscode-textmate#219]
Hello,

I'm not sure if this the right project to report this issue. Please, bear with me 🙏🏻 

I've been annoying for quite some time because of the following PHPdoc highlighting issue:

![code](https://github.com/microsoft/vscode-textmate/assets/57098/1378938c-31dc-4cfd-9a57-d2929876648b)

Is there any way to fix this?

Thanks a lot.

Regards,

**Comment by RedCMD** [comment]
should move to https://github.com/KapitanOczywisty/language-php

**Comment by Schroeder-hash** [comment]
Still  not resolved in `1.117.0`

<img width="506" height="63" alt="Image" src="https://github.com/user-attachments/assets/b8965582-5ae8-48f4-bda3-10d01c85d7c3" />

<img width="506" height="63" alt="Image" src="https://github.com/user-attachments/assets/5f798f89-8906-4464-b238-4e147bddab9e" />

Doesn't matter whether the whitespace is after the comma or after the closing tag, the coloring is off.
