### ISSUE TITLE
onig_scanner.node is not a valid Win32 application

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode-textmate#23]
If I clone [this repo](https://github.com/NigelRook/erlang-grammar) which exposes vscode-textmate as a simple REPL for testing scopes and run tools/tokenize.js, everything works fine.

But if I try to reference this package in a vscode extension, when I call `grammar.tokenizeLine` I get an error: `Error: %1 is not a valid Win32 application.\r\n\\?\c:\Users\path\to\extension\node_modules\oniguruma\build\Release\onig_scanner.node`

Any idea why this is?

**Comment by alexandrudima** [comment]
It looks like `npm install .` failed to compile the native node module `oniguruma`?

Here are the steps to get the C++ toolchain installed on your machine:

https://github.com/nodejs/node-gyp#installation

**Comment by hoovercj** [comment]
I've done this and it still didn't work. A little more research makes me think the issue is that I have x64 node? I'll try running `npm install` to compile it with x86 node later and see if that helps.

**Comment by alexandrudima** [comment]
Yeah, especially if you use `nvm` or you have recently switched node versions, it is possible that you have compiled the native node module for the wrong node version. I suggest to do a `git clean -xfd` (**will remove everything as if you cloned fresh!**) in `vscode-textmate` and run again `npm install .`. You can then monitor the output and see what the C++ compilation is doing.

**Comment by hoovercj** [comment]
What node version should I be using? I tried 32-bit versions of 6.6.0 and 6.3.0 and I got a different error. I'm not sure if it is a step forward or backward:

`Error: A dynamic link library (DLL) initialization routine failed.\r\n\\?\c:\path\to\extension\node_modules\vscode-textmate\node_modules\oniguruma\build\Release\onig_scanner.node`

**Comment by alexandrudima** [comment]
@hoovercj  Can you please start fresh. All the messages you are getting indicate (from me googling them) that the native node module got somehow built for the wrong node version target.

Do it all inside one console without closing it in between the steps (to be certain to get the same environment).

* step1: `git clone https://github.com/Microsoft/vscode-textmate.git`
* step2: `cd vscode-textmate`
* step3: `npm install .`
* step4: `npm run compile`
* step5: `npm run test`

If this does not work, please post in here all the output you get at each step and then we can go ask the node-gyp folks for further guidance.

**Comment by hoovercj** [comment]
Yes, I can try that tonight and let you know. Thanks!

What I'm trying to do, though, is use vscode-textmate in my own vscode extension until a proper API surfaces token information.

To accomplish that, do I need to do the steps above and copy it over to my extension? Because simply adding vscode-textmate to my extension's package.json isn't working.

**Comment by alexandrudima** [comment]
Oh, finally the errors you're getting make sense ! ;)

In VSCode the runtime is not node, but electron. Therefore, you would need to compile `oniguruma` (the native dependency of `vscode-textmate` against the exact same electron version as VSCode ships with.

In stable/1.5.x that would be electron v0.37.6 and in insiders/1.6.x electron v1.3.5

For insiders/1.6.x Windows (from me looking at vscode's `script\npm.bat`) the following environmental variables would be needed to get node-gyp to compile against the same electron version as VSCode:

```bat
set npm_config_disturl="https://atom.io/download/atom-shell"
set npm_config_target=1.3.5
set npm_config_arch="ia32"
set npm_config_runtime="electron"
set HOME=~\.electron-gyp
:: Now you can use npm
npm install .
```

That being said, you would need to compile `vscode-textmate`'s oniguruma on Windows, Mac and Linux 32/64 bit to get your extension working across all OSes. And you would need to implement some switching loading logic on your side, as node's require will not do that for you out of the box.

If I were you, I'd try loading the `vscode-textmate` that already ships with vscode (the OS problem is solved). It is pretty black-magic, but you could load it via:
```js
var tm = require(path.join(require.main.filename, '../../node_modules/vscode-textmate/release/main.js'));
```

**Comment by hoovercj** [comment]
Great, thanks! This seems to be working now.

Just as an added note in case anybody else finds this, I'm trying to use this in a language server extension so I have to evaluate `require.main.filename`  in the language client and pass it over with the `initializationOptions` to get the right value.
