### ISSUE TITLE
[Idea] markdown in js extension

### ISSUE THREAD

**Issue by piscopancer** [microsoft/vscode-textmate#231]
I am no expert in creating textmate extensions for vscode, but if you can, i think you would like trying to make syntax highlight for js/jsx/ts/tsx files like below

![image](https://github.com/microsoft/vscode-textmate/assets/109352196/afc04bce-e00a-414a-8c05-89256ee53346)

https://github.com/bashmish/es6-string-css

**Comment by RedCMD** [comment]
https://marketplace.visualstudio.com/items?itemName=ruschaaf.extended-embedded-languages should do the trick
