### ISSUE TITLE
Give more context: Grammar is in an endless loop - Grammar is not advancing, nor is it pushing/popping

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode-textmate#36]
Moved from Microsoft/vscode#9340
From @bpasero

---

Just noticed this in selfhost, is there any chance we could print more info on the error like the resource that caused it?

![image](https://cloud.githubusercontent.com/assets/900690/16875291/fd7c6edc-4a9e-11e6-8ece-fa3ff2dbab6c.png)

**Comment by tvvignesh** [comment]
I am getting the same error in vscode console.
