### ISSUE TITLE
Multiple ScopeName Configurations

### ISSUE THREAD

**Issue by DHedgecock** [Microsoft/vscode-textmate#45]
Hello, I need to specify language configurations for different scopes in the same file. Specifically I'm making a grammar that highlights tagged template strings for Ember components. In the `source.js` scope I need comment bindings to use JS comment bindings, and inside the `meta.source.glimmer` scope (which is inside the tagged template string), I need comment bindings to use Handlebars comments: `{{! }}`

We're currently doing this in an Atom plugin by using grammar injection, but I see that grammar injection is not supported in VSCode, is that correct?

If this isn't the correct repo for this issue let me know.

Thanks

**Comment by alexandrudima** [comment]
You could do what we do for HTML.

In the `package.json` of your extension, you can "teach" VS Code that your language grammar contains embedded languages that should have different configurations. e.g.

https://github.com/Microsoft/vscode/blob/f58de870d79c7cc785945ab8cf7447df7d38ef52/extensions/html/package.json#L57
```
 "grammars": [
      {
        "language": "html",
        "scopeName": "text.html.basic",
        "path": "./syntaxes/html.json",
        "embeddedLanguages": {
          "text.html": "html",
          "source.css": "css",
          "source.js": "javascript",
          "source.python": "python",
          "source.smarty": "smarty"
        }
      }
],
```

When the scopes (prefix matched) listed in `embeddedLanguages` are encountered, VS Code will change the language from the top-level one to the one specified.

|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/32839077-763a62a8-ca13-11e7-8583-614cbdc8b945.png) | ![image](https://user-images.githubusercontent.com/5047891/32839095-8959f6c8-ca13-11e7-9fe5-a80100f62dc5.png) |

**Comment by DHedgecock** [comment]
Thanks @alexandrudima works!
