### ISSUE TITLE
HTML injection rule not correctly handled

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-textmate#46]
The html grammar has the following 'R' injection rule which is not handled in vscode textmate
```
	"injections": {
		"R:text.html - (comment.block, text.html source)": {
			"comment": "Use R: to ensure this matches after any other injections.",
			"patterns": [
				{
					"match": "<",
					"name": "invalid.illegal.bad-angle-bracket.html"
				}
			]
		}
	},
```

2 issues
- comma in expressions not expected (it was assumed that it can only be top level)
- R: not handled

**Comment by aeschli** [comment]
The HTML sample to see the issue is:
```
<html>
<head>
    <script>
    //dd<dd<dd
    </script>
</head>
<html>
```

**Comment by SDP190** [comment]
@aeschli thanks for the fix, i guess it will be available to the public at the next release of VSCode.

**Comment by infininight** [comment]
@aeschli Is there any any documentation on what grammar features are supported in VSCode's TextMate grammar support? It's the black hole in my knowledge of editors that use the grammars.

**Comment by aeschli** [comment]
@SDP190 In VSCode we only use the pattern section of the tmLanguage files. We have our own configuration files for the language definition (language id, name, associations, firstLine) and configuration (folding, ...).

But for the tokenization rules, we want to be fully compatible to TextMate. As there is not much specification we still find gaps from time to time.

Did you have a particular gap in mind?

**Comment by infininight** [comment]
@aeschli No gap in mind. Just was wondering if any list of differences existed, no problem that there isn't. I guess one thing that does come up in esoteric cases is which regex engine is used, GitHub uses a different engine so there are a few gotchas we watch out for there.
