### ISSUE TITLE
Problems in syntax highlighting after backticks in Javascript

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode-textmate#55]
In this JS code:
```js
//
Relay.injectNetworkLayer(
  new Relay.DefaultNetworkLayer(`${window.location.origin}/graphql`, {
    credentials: 'same-origin',
  }),
);

function loadStories() {
  const context = require.context('../src/', true, /__stories__\/.+\.js$/);
  context.keys().forEach(context);
}
```
The `loadStories` function has barely any highlighting, and even comments are incorrectly highlighted after a string interpolation:

![image](https://user-images.githubusercontent.com/760112/31128498-a1ab8400-a86f-11e7-900c-ead16ad1826c.png)

**Comment by mjbvz** [comment]
I believe this is fixed in the current vs code insiders:

![screen shot 2017-10-30 at 11 44 27 am](https://user-images.githubusercontent.com/12821956/32189345-b836ea4a-bd67-11e7-95eb-c22a2e8915d2.png)

Please file language specific bugs against the main vscode repo
