### ISSUE TITLE
C's preprocessor directive #ifdef/#endif grays out code

### ISSUE THREAD

**Issue by Leedehai** [Microsoft/vscode-textmate#63]
example 1:
<img width="332" alt="screen shot 2018-02-22 at 16 47 06" src="https://user-images.githubusercontent.com/18319900/36572375-526ac3a6-17f0-11e8-9d01-4968ae763e36.png">
example 2:
<img width="272" alt="screen shot 2018-02-22 at 16 47 37" src="https://user-images.githubusercontent.com/18319900/36572377-5298b82e-17f0-11e8-94e5-b586d8f2701b.png">
example 3:
<img width="325" alt="screen shot 2018-02-22 at 16 48 16" src="https://user-images.githubusercontent.com/18319900/36572378-52afd9e6-17f0-11e8-98b2-ed039bd52bd8.png">

Though not defined in code, those symbols (`FILESYS`, `USERPROG`..) are to be passed in by the compiler (GCC's `-D` option), so the code segments are, in fact, active. Textmate shouldn't act on its own and render them as inactive.

**Comment by alexandrudima** [comment]
This is something specific about a specific TM grammar, so it is IMHO not an issue with vscode-textmate -- the engine that interpretes the grammar. So, please find the location of the grammar you are using and file an issue there.

**Comment by aeschli** [comment]
The graying out is a feature of the [cpp extension](https://github.com/Microsoft/vscode-cpptools). It happens on top of the syntax highlighting using decorators.
