### ISSUE TITLE
Possible to run in the browser?

### ISSUE THREAD

**Issue by epatpol** [microsoft/vscode-textmate#65]
From what I understand at least the dependency to oniguruma (node module) currently makes it impossible to use in a browser environment, but what if [onigasm](https://github.com/NeekSandhu/onigasm) was used, would there be other impediments to make it work in the browser?  It says [here](https://code.visualstudio.com/blogs/2017/02/08/syntax-highlighting-optimizations) that interpret textmate grammars in the browser is not currently possible. Care to elaborate on this?

Thanks!

**Comment by czb** [comment]
Would also love to see oniguruma in the monaco editor. ;) BTW: It has also been discussed here:

https://github.com/Microsoft/monaco-editor/issues/171

**Comment by alexandrudima** [comment]
This can be run in a browser and it has been run.

See https://github.com/Microsoft/vscode-textmate/pull/44

**Comment by epatpol** [comment]
Thanks for the comment @alexandrudima, I didn't really get the PR, but from what I understand it would be needed as a first step to make it work in the browser right? By using another implementation of oniguruma, I don't know if onigasm or anything was mentionned in this case, but was that the goal?

**Comment by NeekSandhu** [comment]
I just released [monaco-textmate](https://github.com/NeekSandhu/monaco-textmate#using).

It's browser version of `vscode-textmate`. You should be able to wire it up `monaco-editor` (or any editor really)

**Comment by epatpol** [comment]
@NeekSandhu That's amazing. I'm going to try it out some time tomorrow and report back if needed. Thanks for the update.

**Comment by czb** [comment]
wow, great ;). BTW: do you know how to wire it into monaco editor?

**Comment by NeekSandhu** [comment]
I just published a module to wire `monaco-textmate` with `monaco-editor` - [monaco-editor-textmate](https://github.com/NeekSandhu/monaco-editor-textmate)
___
If you guys would like to help me, I'd really appreciate if you guys could star and bump these issues:
 - [Allow extensions to call `ExtensionPanel.show()` to focus their panel | ChromiumBugs](https://bugs.chromium.org/p/chromium/issues/detail?id=834203)
 - [Expose element inspection API for devtools extensions | ChromiumBugs](https://bugs.chromium.org/p/chromium/issues/detail?id=811036)

Thoses issues aren't moving forward but are very critical to me. Consider commenting something to get devs attention :)

**Comment by czb** [comment]
Perfect, thanks a lot ;) I have starred both issues.

BTW: How do you load a color theme into monaco from a json file (e.g. `dark_plus.json`?

**Comment by NeekSandhu** [comment]
Thanks mate!!

Unfortunately, that remains a bummer. Looking at [how it's currently done](https://microsoft.github.io/monaco-editor/playground.html#customizing-the-appearence-tokens-and-colors), `monaco-editor` doesn't provide any interface to inject TM themes. Although I'm pretty sure `monaco-editor`'s theming engine **has** that capability. It's up to monaco team if they'd be willing to expose that feature to allow devs to tap into the good stuff.

I'd recommend this amazing article by @alexandrudima - [Optimizations in Syntax Highlighting > TextMate themes](https://code.visualstudio.com/blogs/2017/02/08/syntax-highlighting-optimizations#_textmate-themes)

**Comment by czb** [comment]
@epatpol can you confirm that? - that there is currently no way to inject TM theme into the monaco editor?

From what is mentioned here:

https://github.com/Microsoft/monaco-editor/issues/171

> we have experimented with Emscriptem to compile the C library to asm.js, but performance was very poor even in Firefox (10x slower) and extremely poor in Chrome (100x slower).

I would assume there is probably an hidden way to do it 👍

**Comment by NeekSandhu** [comment]
> we have experimented with Emscriptem to compile the C library to asm.js, but performance was very poor even in Firefox (10x slower) and extremely poor in Chrome (100x slower).

I believe that only applies to `.tmGrammars` and not `.tmThemes`, since the former requires fancy Regex engine to do it's thing and latter is just plain JSON that says foreground shall be `#0366d6` when a token is `source.js string.literal.js`. So shouldn't be a challenge I guess.
