### ISSUE TITLE
Unexpected highlighting behavior when end is not defined

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-textmate#66]
_From @mhchem on April 25, 2018 9:20_

With this simplified `.tmLanguage` file, the whole document should be formatted a comment (because I use a `begin` without and `end`).

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>text.test</string>

        <key>patterns</key>
        <array>
            <dict>
                <key>begin</key><string>^.</string>
                <key>name</key><string>comment</string>
            </dict>
            
            <dict>
                <key>begin</key><string>.</string>
                <key>name</key><string>invalid</string>
            </dict>
        </array>
    </dict>
</plist>
```

This works fine unless the document contains the word `undefined`.

![image](https://user-images.githubusercontent.com/16336692/39236297-bfc5b81c-4878-11e8-8286-7b49a1ccba3e.png)

I guess this is a "`end` is undefined" issue where `undefined` is taken literally.

The issue can be avoided by setting `end` to a never-matching regexp (like `<key>end</key><string>^\b$</string>`). And maybe that could be put into the highlighting code: if undefined, use `^\b$` instead of the string `undefined`.

_Copied from original issue: Microsoft/vscode#48654_

**Comment by alexandrudima** [comment]
I think we never ran into this because a grammar with a `begin` statement and a missing `end` statement is illegal... So our resolution could be to throw the entire rule out.

**Comment by mhchem** [comment]
It's your decision. All I can say is that I read the documentation differently. (My understanding of "If there is no match for the end pattern, the end of the document is used." was that I can leave out the `end` to achieve a match till the end of the document.)

**Comment by RedCMD** [comment]
> the whole document should be formatted a comment (because I use a `begin` without and `end`).

no actually

Testing TextMate 2.0 on Mac:
if `end` is NOT present
TextMate will then convert the `begin` into `match`!
meaning `beginCaptures` and `patterns` now no longer work

textmate will still do this even if `begin` AND `end` exists!
for example if you have `match`, `begin` AND `end` defined
TextMate will ignore `begin` and use instead use `match` instead with the `end`!!
meaning `beginCaptures`, `patterns` and `applyEndPatternLast` will still work
