### ISSUE TITLE
inspect.js uses grammer_paths[0] in loop to enumerate all grammers.

### ISSUE THREAD

**Issue by msftrncs** [Microsoft/vscode-textmate#72]
Realized while testing the html <script> issue that the header of the output indicated that the inspect process was just pulling the HTML syntax twice, and I wasn't seeing any JavaScript syntax hits.

The grammer loading `for` loop in 'inspect.js' was just always referring to grammer_paths[0].

Will post a PR.

**Comment by alexandrudima** [comment]
Fixed by #73
