### ISSUE TITLE
Clarify details in documentation

### ISSUE THREAD

**Issue by gwk** [microsoft/vscode-textmate#76]
I think the following are true but I'm not sure; could the readme please be updated to answer these essential questions?

* This is the library that VSCode uses to process extension syntax files.
* The regex dialect used is Oniguruma: https://github.com/kkos/oniguruma
* Which version of Oniguruma is currently used by VSCode and VSC Insiders?

Thanks!

**Comment by alexandrudima** [comment]
9e46129c8dc384baf4eeea2e3eae42c8790ecb41
