### ISSUE TITLE
Character "<" color incorrectly handled on HTML document property values

### ISSUE THREAD

**Issue by lmorelato** [microsoft/vscode-textmate#89]
The issue described in this link happens to me for HTML property values:
https://github.com/Microsoft/vscode/issues/26495

Is there any kind of special configuration or workaround dealing with it, or it is a real issue?

![image](https://user-images.githubusercontent.com/12112408/54479312-e10e1e00-47f1-11e9-9689-242a48256f2f.png)

Thank you.

**Comment by lmorelato** [comment]
It can be reproduced with:

`
        <html>
        <div data-test="x < 0" data-test="x > 0">
        </div>
        </html>
`

![image](https://user-images.githubusercontent.com/12112408/54479414-c2f4ed80-47f2-11e9-9c84-989c343870e6.png)

**Comment by msftrncs** [comment]
@lmorelato, the `<` character is an invalid character inside a tag attribute, and it must be escaped with `&lt;`, however you might find that not all browsers require it.  The colorizing that you are seeing is created by the HTML grammar which comes from TextMate.  On the other side, `>` does not require escaping.  These results have nothing to do with this repository particularly, it appears to be processing TextMate's HTML grammar file correctly in this area.

Potential reference: https://stackoverflow.com/questions/9187946/escaping-inside-html-tag-attribute-value

**Comment by alexandrudima** [comment]
The HTML grammar in VS Code is the one at https://github.com/textmate/html.tmbundle . If you feel that a change is needed in the grammar, please feel free to open an issue directly against the grammar repository.

This project is an interpreter for grammars, so it does not contain the truth of any grammars, the grammars included in this repository are only used as fixtures.
