### ISSUE TITLE
How do I change registry.loadGrammar to not return promises?

### ISSUE THREAD

**Issue by ChrisMGeo** [microsoft/vscode-textmate#93]
Hello, I'm pretty new to JS and am using this npm package for tokenizing text for making a syntax highlighter. However I'm pretty new to promises and as such don't know how to return `grammar.tokenizeLine()` in the example code given in the home-page. How do I return the grammar then? Sorry for the inconvenience.

**Comment by msftrncs** [comment]
I unfortunately don't know much about JS/TS either, but for a potential example, look at the inspect script:

https://github.com/Microsoft/vscode-textmate/blob/8870575f0a42eb75d035d93f60c6ba8fb795fc2a/scripts/inspect.js#L37-L66

Be aware I think there are some errors the code above, see issue #91 and PR #92.

Hoping this helps.

**Comment by ChrisMGeo** [comment]
Thanks @msftrncs , however I don't think this is what I'm looking for however I have found something that I was too dumb to find. In the example code we instantiate a registry class with loadGrammar as a function to return something, in the example code this is a promise(which was the promise which I had to .then, but couldn't return anything from), so I'm guessing to change loadGrammar to something else so that instead of a promise it returns the grammar.

**Comment by ChrisMGeo** [comment]
I think I'm getting close as I tried the following code:
```
var fs = require("fs");
var vsctm = require('vscode-textmate');

function codeToScopes(code, language_loc){
var grammar = vsctm.parseRawGrammar(fs.readFileSync(language_loc).toString(), language_loc)
console.log(grammar);
}

```
However I get the _grammar from the actual grammar object. To prove this run the following code:
```
var fs = require("fs");
var vsctm = require('vscode-textmate');

function codeToScopes(code, language_loc){
var grammarPaths = {
  'source.js': language_loc
};
var registry = new vsctm.Registry({
	loadGrammar: function (scopeName) {
		var path = grammarPaths[scopeName];
		if (path) {
			return new Promise((c,e) => {
				fs.readFile(path, (error, content) => {
					if (error) {
						e(error);
					} else {
						var rawGrammar = vsctm.parseRawGrammar(content.toString(), path);
						c(rawGrammar);
					}
				});
			});
		}
		return null;
	}
});

// Load the JavaScript grammar and any other grammars included by it async.
registry.loadGrammar('source.js').then(grammar=>{
  console.log(grammar);
})
}

```

**Comment by msftrncs** [comment]
You would use the 'grammar' object returned from the 'then' method of the promise.  Take the last few lines from your example:

```JavaScript
// Load the JavaScript grammar and any other grammars included by it async.
registry.loadGrammar('source.js').then(grammar=>{
  var ruleStack. = null;
  console.log(grammar.tokenizeLine('a line of text', ruleStack));
})
}
```

This probably won't output anything meaningful, but should help.  Its exactly how its down in the inspect.js script, but further up from where I linked to.

**Comment by alexandrudima** [comment]
I have updated README.md to have a better example.
