### ISSUE TITLE
Unit testing tmLanguage files [question]

### ISSUE THREAD

**Issue by PanAeon** [microsoft/vscode-textmate#98]
Hi,
I've written a [tool](https://github.com/PanAeon/vscode-tmgrammar-test) that allows to write assertions in a plaintext file against a textmate grammar, like so:
```scala
      def add(x:Int,y:Int) = x + y
          ^^^ entity.name.function.declaration
```
I use vscode-textmate to run the actual grammar internally. It is very similar to [Sublime syntax tests](https://www.sublimetext.com/docs/3/syntax.html#testing) but I've made a few deviations. 

So, I thought maybe someone can take a look at it and if finds it useful maybe we can put some links in the documentation. What do you think?

**Comment by alexandrudima** [comment]
:+1: Nice! a3f92e1396d1d1a43eb95a0c142c7966e50ba2dc
